services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka-local
    ports:
      - "9092:9092"

    environment:
      # ==========================================
      # KRaft Configuration
      # ==========================================
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # ==========================================
      # Listeners
      # ==========================================
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

      # ==========================================
      # Listener Protocols
      # ==========================================
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # ==========================================
      # Controller
      # ==========================================
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # ==========================================
      # Single Broker Settings
      # ==========================================
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # ==================================================
  # KAFKA UI
  # ==================================================

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-local
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092


  # ==================================================
  # TIMESCALE DB
  # ==================================================

  timescaledb:

    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: timescaledb-local
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: traffic_db
      POSTGRES_USER: traffic_user
      POSTGRES_PASSWORD: traffic_password

    volumes:
      - timescaledb_data:/var/lib/postgresql/data


  grafana:
    build:
      context: .
      dockerfile: grafana-image/Dockerfile
    image: grafana-custom:latest
    container_name: grafana-local
    depends_on:
      - timescaledb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      # Keep Grafana dashboards/settings/data
      - grafana_data:/var/lib/grafana

      # Automatically load alert rules
      - ./grafana/provisioning:/etc/grafana/provisioning


volumes:
  timescaledb_data:
  grafana_data: